# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Arrows                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

right_format = """\
$cmd_duration\

"""

format = """
$username$hostname$directory
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[🭧🭒](bold fg:#90b7f6)[ ➜ ](bold bg:#90b7f6 fg:#000000)[](bold fg:#90b7f6)"

error_symbol = "[🭧🭒](bold fg:#ad90f6)[ ✗ ](bold bg:#ad90f6 fg:#000000)[](bold fg:#ad90f6)"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold #ad90f6)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](#90b7f6)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[ ](bold bg:#ad90f6 fg:#90b7f6)[$hostname](bg:#ad90f6 bold fg:#000000)[ ](bold fg:#ad90f6 bg:#e890f6)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed #90b7f6"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#90b7f6 fg:#000000"
style_root = "red bold"
format = "[🭃](bold fg:#90b7f6)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bold bg:#e890f6 fg:#000000"
truncation_length = 2
truncation_symbol = "./"
format = '[$path]($style)[🭞](fg:#e890f6)'


[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
min_time = 0
format = '[🬈🬖🬥🬅 ](bold bg:#f5d773 fg:#000000)[time:$duration](bold bg:#f5d773 fg:#000000)[ 🬖🬥🬔🬗](bold bg:#f5d773 fg:#000000)'
